### ISSUE TITLE
When I upload the data from excel file, some of the column data concatenated with % symbol, so when I check the database it calculated percentage value. Ex: 50% converting to 0.5 

### ISSUE THREAD

**Issue by venkat2121** [antonscheffer/excel2collections#3]

**Comment by antonscheffer** [comment]
When you in Excel type 3%, Excel converts that to a number 0.03 and displays it as 3%. Excel2Collections loads the converted number, because it doesn't look at the way Excel displays its numeric (or date or string) values. You might store it in Excel as text if you don't want this to happen.
