### ISSUE TITLE
Minor issue 

### ISSUE THREAD

**Issue by OzDeadnut** [antonscheffer/excel2collections#5]
Hi Anton, I found a minor bug with the plugin.
If a field has a value of .7 an error occurs where it is changed to 7.0000000000000007E-2.
If the value is 0.7 it works.
This is an awesome plugin great work

**Comment by antonscheffer** [comment]
Hi, maybe a little late, but do you can give me an example file which shows this?

**Comment by antonscheffer** [comment]
I can not reproduce this
