### ISSUE TITLE
EXCEL2COLLECTION must be declared error

### ISSUE THREAD

**Issue by singaraxilinx** [antonscheffer/excel2collections#6]
getting below error and confirmed no change was done at Database level. the plugin was running fine for last 2 years and suddenly this issue from no where.

_ORA-06550: line 3, column 12: 
PLS-00201: identifier 'EXCEL2COLLECTION.TP_SHEETS' must be declared ORA-06550: line 3, column 12: 
PL/SQL: Item ignored ORA-06550: line 8, column 3: 
PLS-00201: identifier 'EXCEL2COLLECTION.SET_BLOB' must be declared ORA-06550: line 8, column 3: 
PL/SQL: Statement ignored ORA-06550: line 20, column 3: 
PLS-00320: the declaration of the type of this expression is incomplete or malformed ORA-06550: line 20, column 3: 
PL/SQL: Statement ignored ORA-06550: line 21, column 17: 
PLS-00320: the declaration of the type of this expression is incomplete or malformed ORA-06550: line 21, column 3: PL/SQL: Statement ignored ORA-06550: line 44, column 3: 
PLS-00201: identifier 'EXCEL2COLLECTION.FREE_BLOB' must be declared ORA-06550: line 44, column 3: 
PL/SQL: Statement ignored ORA-06550: line 47, column 11: 
PLS-00201: identifier 'EXCEL2COLLECTION.GET_LOG' must be declared ORA-06550: line 47, column 5: PL/SQL: Statement ignored_

**Any thoughts how to go about as not able to find any problem so far.**

![apex_excel2coll_error](https://user-images.githubusercontent.com/87065150/124728767-6e855700-df42-11eb-9460-c3937570db22.jpg)

**Comment by antonscheffer** [comment]
That is no issue which suddenly popped up. Since version 0.902 (february 2018) the plugin checks for the existence of a database package. When found it uses that package, when not found it continues using the plugin code. You can see that in the debug logging, it just continues:
try old method
parsing xlsx
parsing xlsx
read sheet1
parsed, 1 sheets found

So no issue :)
