### ISSUE TITLE
 identifier 'EXCEL2COLLECTION.TP_SHEETS' must be declared

### ISSUE THREAD

**Issue by sharedoyle** [antonscheffer/excel2collections#7]
I am getting the following error when I try to run the EXCEL2COLLECTION process
PLS-00201:  identifier 'EXCEL2COLLECTION.TP_SHEETS' must be declared

<img width="509" alt="Screenshot 2023-08-15 121443" src="https://github.com/antonscheffer/excel2collections/assets/142334668/7c562b58-20c0-44b6-b12f-b760753f40fa">

**Comment by antonscheffer** [comment]
The error "PLS-00201: identifier 'EXCEL2COLLECTION.TP_SHEETS' " is something you can ignore. 
The second error  "ORA-06502: PL/SQL: numeric or value error" is more serious. That means it can not parse the XLS-file. Without that file it is impossible to say why that is happening.

**Comment by antonscheffer** [comment]
You could try that XLS-file at my demo application for this plugin at [Demo application for EXCEL2COLLECTION](https://apex.oracle.com/pls/apex/f?p=33308)
That application uses the "package-parser" which, besides being much faster, provides more logging for me to debug.

**Comment by antonscheffer** [comment]
I removed the code to try using "a" package.
